version: '3.9'

services:

  acetl_database:
    image: /postgres/latest
    restart: always
    environment:
      POSTGRES_DB: acetl_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    container_name: acetl_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/bitnami/postgresql/


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    container_name: acetl_pgadmin
    ports:
      - "5052:80"
    volumes:
      - postgres_data:/var/lib/pgadmin


volumes:
  postgres_data: