version: '3.9'

services:

  acetl_web_application:
    build:
      context: .
      dockerfile: acetl.web.Dockerfile
    restart: always
    environment:
      # App Config
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      # database config
      DATABASE_HOST: acetl_database
      DATABASE_PORT: 5432
      DATABASE_NAME: acetl_database
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
    depends_on:
      - acetl_database
    container_name: acetl_web_application
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  acetl_database:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: acetl_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    container_name: acetl_database
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/bitnami/postgresql/


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    container_name: acetl_pgadmin
    ports:
      - "8080:80"
    volumes:
      - postgres_data:/var/lib/pgadmin


volumes:
  postgres_data: